### ISSUE TITLE
ng build --prod breaks this

### ISSUE THREAD

**Issue by nassan** [jesusbotella/ngx-lazy-load-images#9] opened 2017-12-31 09:28 UTC
I have a component which I bind an @Input, `[attr.data-src]="url". When the map files are loaded and in `ng serve` the functionality works fine, but when I build for production, it doesn't work. I see in the dom inspector that the attr.data-src is still on the img tag, and in my component the function that I attach to the img.onload does not get fired. Any thoughts as to why this is happening?

**Comment by jesusbotella** [comment] 2018-01-11 21:04
Hey @nassan! Sorry for my late reply

It seems like the library is not being included in your production build. It could be really great if you can inspect your production generated JS files and look for `querySelectorAll('img[data-src], [data-srcset], [data-background-src]')` or a subset of that string. If there is any coincidence, the library is inside the bundle.

I will try to debug a production build to see if I can reproduce the error you described. I will get back at you as soon as I have any solution to the problem.

**Comment by jesusbotella** [comment] 2018-01-17 20:28
Sorry for the delay, let me check what happens today and I will come with a fix as soon as possible.

**Comment by jesusbotella** [comment] 2018-01-17 23:25
Can you please check the latest release? I included a fix for this issue and I want you to tell me if it works for you or not.

**Comment by amit0choubey** [comment] 2018-01-18 07:52
Hi Jesus,

Thanks for the fixing the issue on priority. Lazy load module is working
fine now.
Can you please brief us what went wrong suddenly so that it won;t affect
our production application in future?

Thanks and Regards
Amit Choubey

**Comment by jesusbotella** [comment] 2018-01-18 13:20
It's great that the fix is working as expected :)

You can see the fix [here](https://github.com/jesusbotella/ngx-lazy-load-images/commit/2ab8168). The directive was not replacing the image data attributes because it was being attached after the nodes were inserted into the DOM, so the `MutationObserver` callback was not fired.

What I did to fix it is as simple as calling that callback once to check the current DOM nodes and replace its attributes if needed.

**Closed** 2018-01-25 23:01 UTC
